### ISSUE TITLE
Unable to understand how to run this

### ISSUE THREAD

**Issue by atomicsyed-99** [lajobu/CNN_glasses_no_glasses#1]
Hey , I wanted to know how to run this model? Please do help me out

**Comment by lajobu** [comment]
Hi, take a look to this Kaggle notebook, I published the code and model over there: https://www.kaggle.com/jorgebuenoperez/computer-vision-application-of-cnn

**Comment by atomicsyed-99** [comment]
Hey Jorge!,
Thanks for the reply. However I wanted to know if I want to run the same
code in google colab, what changes would I have to do in the code,
especially with the files where you have stored the paths to the respective
images of each type.

Thanks and Regards,
Syed

**Comment by lajobu** [comment]
I never used google colab, however, you have two options:
1)  Download this data: https://www.kaggle.com/datasets/jorgebuenoperez/datacleaningglassesnoglasses - you will see that in 'Images/Images' there are two folders 'glasses' and 'no_glasses', these two folders contain all the images divided by class, you can use this two to train the model. However, this will require changes in how the data input is read
2) The paths that you mention which are in the three .txt files are linked to the original data source: https://www.kaggle.com/datasets/jeffheaton/glasses-or-no-glasses, so you can download this one and use the three .txt files

**Comment by atomicsyed-99** [comment]
Hey Jorge!,
Thanks a lot , I ran the notebook and its working perfectly fine, how do I
run it on any random image that I give as a test input? Like if I take any
random image from the web and give it as an input for prediction, how do I
do that?

Thanks and Regards,
Syed

**Comment by atomicsyed-99** [comment]
Hey Jorge,
Could you help me out with this single image testing?
Thanks and Regards,
Syed
